### ISSUE TITLE
 PID maintenance statistics: Feature doesn’t seem to work properly

### ISSUE THREAD

**Issue by doshipriyank** [cdlib/pid#7]
PID maintenance statistics: Feature doesn’t seem to work properly.  Dates with days 13 or higher retrieve zero results (e.g., 04/30/2015).  Months and years are unaffected.  Results are inconsistent and may be inaccurate.

**Comment by briri** [comment]
FYI,
I think this is related to bug #2. 

If you enter the date as 2015-08-01 and 2015-08-31 you get the correct results. If you use the recommended 08/01/2015 and 08/31/2015 you do not get results. 

This uses the HTML5 date input type. Chrome provides a nice date picker widget and displays the selected date as 08/01/205. Firefox though does not provide a date picker and for some reason wants it in the other format (Chrome might be sending it to the server in the yyyy-mm-dd format during the form post).

Might be a good idea to abandon the date input type and just add some JS validation instead.
